### ISSUE TITLE
Possibility for Default/Additional Dimensions for Metrics?

### ISSUE THREAD

**Issue by mhamrah** [signalfx/signalfx-istio-adapter#5]
We segment our system by environment, and I'd like to auto-add dimensions like `env:production` to all metrics. I can do this for spans via the smart-gateway, but it does not appear to apply to metrics when I set the ingest url to our smart-gateway. 

Another alternative is to add the additional dimensions upstream (i.e. the metrics crd?0 but I wasn't able to figure that out.

**Comment by keitwb** [comment]
Are those dimensions derivable from the Istio attribute vocabulary somehow (e.g. `source.labels`) or are they just something you want to hardcode in the Istio adapter config?

**Comment by mhamrah** [comment]
They are not derivable, just hard coded values (preferably coming from a
config map).  In order to add I believe I need to update the attribute
manifest, but not sure how to populate.

**Comment by mhamrah** [comment]
Yup, thanks .
