### ISSUE TITLE
Add support for rewriteClientSpanId

### ISSUE THREAD

**Issue by mpetazzoni** [signalfx/signalfx-istio-adapter#7]
We need to add support for rewriting shared span IDs similar to what's done with `rewriteClientSpanId` in the Stackdriver adapter (and make it default to `true`) to ensure that shared spans are correctly "split" into a client-side span and a server-side span with different IDs.

See https://github.com/istio/istio/blob/master/mixer/adapter/stackdriver/trace/trace.go#L164 for a reference implementation in the Stackdriver adapter. The concept is that the client-side span's spanId and the server-side span's parentId are both being rewritten in a deterministic way.

Without this feature the SignalFx Istio mixer adapter sends shared spans to SignalFx, which is not yet supported in the backend.

/cc @mhamrah

**Comment by mhamrah** [comment]
+1. We're running a forked istio-proxy container that sets Envoy's `shared_span_context` explicitly, but doesn't appear to be working.
