### ISSUE TITLE
Incorrect LocalEndpoint Mapping

### ISSUE THREAD

**Issue by mhamrah** [signalfx/signalfx-istio-adapter#9]
According to [the uAPM docs](https://docs.signalfx.com/en/latest/apm/apm-overview/apm-metadata.html) the `service` dimension is mapped to `localEndpoint.serviceName`, which is mapped from a config value, the default being `source.workload.name`. 

I believe this to be incorrect in the case of a server span (kind: server), as `source.workload.name` is not the local endpoint, but the remote, and in this case the local/remote endpoints should be reversed. 

As it currently stands in SFX both client and server spans have the same server name. See traceid `d55b1c305d65b541` in our Namely account as an example.

**Comment by keitwb** [comment]
I'm thinking the simplest way to handle this is to just flip flop the local/remote endpoint mappings if it is a non-client span.
